### ISSUE TITLE
Why are specific layers and convs chosen?

### ISSUE THREAD

**Issue by kirk86** [samaonline/Orthogonal-Convolutional-Neural-Networks#3]
Hi, I'm trying to understand i there's a specific reason for how convs are chosen? 
For instance why are only `conv1` form each layer chosen and not all of them?
Additionally why `orth_dist` is applied to some convs but `deconv_orth_dist` to others?

If I choose another architecture how can I apply this approach, meaning should I apply it to every conv? If so then how do you chose where to apply `orth_dist` and `deconv_orth_dist`?

Thanks!

**Comment by hellozhaozheng** [comment]
Also, I want to ask when should we use `conv_orth_dist`?  Thanks~

**Comment by samaonline** [comment]
Thank you for the interest in this work. I have updated instructions accordingly. Please refer to Q&A section in [README](https://github.com/samaonline/Orthogonal-Convolutional-Neural-Networks/README.md) for answers.

"conv_orth_dist" use to serve as column orthogonality and is depreciated now, since row and column orthogonality has the same loss in our F-norm setting (Lemma 1 in the paper).
